### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by knro** [aceHubert/material-ui-slider#1]
Thanks for making this component! I was looking for a material-ui slider until the official one is released. I tried including this in my project, but I am getting:
`Module not found: Error: Can't resolve 'material-ui-slider' in '....'`

Where ... is the full path to the file where I imported the module:

`import { Slider } from 'material-ui-slider';`

I installed it using npm. Everything else works fine, except for this component. Any clues?

**Comment by marcellobarile** [comment]
I've got the same issue just a few mins ago

**Comment by yuchuan1** [comment]
Me too. I am using material-ui v1.1.0

**Comment by marcellobarile** [comment]
I had to switch to another module. Such a pity :'(

**Comment by knro** [comment]
Yeah I dropped this module and used the @material-ui/lab Slider

**Comment by aceHubert** [comment]
sorry ,which version were you using?

**Comment by aceHubert** [comment]
Sorry, my mistake. published some wrong files with npm. updated.
