### ISSUE TITLE
Slider steps limited to 100

### ISSUE THREAD

**Issue by erpheus** [aceHubert/material-ui-slider#11]
I have a slider than can take values from 0 to 1000 but the events I get are all multiples of ten (450, 460, etc...) so even though my slider is long enough to allow for a finer selection I'm limited to just a 100 steps.

I think the line responsible for this is https://github.com/aceHubert/material-ui-slider/blob/master/src/slider/Slider.jsx#L200 in which the number is divided by a 100 and then rounded. Is there any possibility you could remove this? Or allow an option to remove it at the cost of not being able to use the scale? which I guess is the only thing that could be impacted by such changes.

Thanks a lot anyway for the nice slider though!! It is nice to have an alternative to the buggy material-ui/labs one :)

**Comment by aceHubert** [comment]
@erpheus thanks for report the bug, just came back from trip.
do you have a demo for it, I didn't get it why need it to remove line 200 the divided by a 100.

**Comment by erpheus** [comment]
I'm currently quite busy but I will try to make a demo at some point.

The problem with that divide by 100 line is the rounding actually. It makes the range of the slider have, at most, 100 possible values. I wanted my slider to be able to take any value in my range.

For example, if I make a slider that has 0 and 1000 for min and max values respectively, there is no way to move the slider to the value 501. It would be either 500 or 510, there is nothing in between.

I understand that for small sliders a 100 steps is more than fine, but the one I have occupies the full browser from left to right. It is big enough to support more precision than just 100 steps.

**Comment by aceHubert** [comment]
@erpheus same busy here. I also will try to find it and fix it. Then I will let you know.

**Comment by aceHubert** [comment]
I found the problem and fixed it, please have a look.
