### ISSUE TITLE
Failed to compile issue

### ISSUE THREAD

**Issue by xtaaaal** [aceHubert/material-ui-slider#12]
Hi,

I just npm installed the material-ui-slider, and it comes with "Fail to compile" error as below:

```
./node_modules/material-ui-slider/es5/src/slider/Slider.js
Module not found: Can't resolve '@material-ui/core/styles' in '{MyWorkingFolderPath}\node_modules\material-ui-slider\es5\src\slider'
```

Component code:
`<Slider color="#ff0198" defaultValue={this.state.sliderValue} min={parseInt(sliderRange[0])} max={parseInt(sliderRange[1])} scaleLength={1}/>);`

Library Versions:
"material-ui-slider": "^3.0.3",
"react": "^16.8.6"

**Comment by aceHubert** [comment]
have you installed "@material-ui/core"?  it's in the peerDependencies.
