### ISSUE TITLE
Cannot build locally

### ISSUE THREAD

**Issue by AurelReb** [aceHubert/material-ui-slider#15]
Hi, I can't build your lib locally after forking it. Why?
Btw, I made a pull request for adding new props very useful. Please consider adding it.

**Comment by aceHubert** [comment]
I re-installed the packages and got same problem, because I re-write the "react-scripts", the newest version changed the files, you can try to remove "react-scripts" then install "react-scripts@2.0.5" should work fine.
I will have a look with your request.
